apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: github.com/cloudfoundry/cf-for-k8s
    git:
      url: https://github.com/cloudfoundry/cf-for-k8s
      ref: 9639396e467578497cec0252fce1cc7263b4fe0b
    includePaths:
    - config/**/*
